### ISSUE TITLE
Remake ACF tutorial in Github

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#62]
Currently Hosted on the forums, and would look much nicer on the github, whilst letting people know about the bug tracker!

**Comment by SparkyTM** [comment]
A new window will appear with a field where you can paste in the URL [url=https://github.com/nrlulz/ACF/trunk][color=red]https://github.com/nrlulz/ACF/trunk/color/url and then hit OK.

Replace: [url=https://github.com/nrlulz/ACF/trunk][color=red]https://github.com/nrlulz/ACF/trunk/color/url

With the new link they have: https://github.com/nrlulz/ACF

Heres the link for the SVN, because it looks like you CTRL V'd the thing from the forums.
https://tortoisesvn.net/downloads.html


also [code]C:\Program Files (x86)\steam\SteamApps\common\GarrysMod\garrysmod\particles/code
and [code]C:\Program Files (x86)\steam\SteamApps\common\GarrysMod\garrysmod\addons/code 

need to be fixed because of that pesky CODE
